sonar.projectKey=studentmgmt
sonar.projectName=Student Management System
sonar.sources=src
sonar.tests=test
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.login=your_token_here
sonar.host.url=http://localhost:9000
